/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    Articles: typeof import('./../components/Articles.vue')['default']
    Footer: typeof import('./../components/Footer.vue')['default']
    HelloWorld: typeof import('./../components/HelloWorld.vue')['default']
    Hero: typeof import('./../components/Hero.vue')['default']
    Navigation: typeof import('./../components/Navigation.vue')['default']
    Skills: typeof import('./../components/Skills.vue')['default']
  }
}
